[build]
  # Directorio donde se ejecuta el build
  base = "."
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio donde se encuentran los archivos estáticos generados
  publish = "dist"

[build.environment]
  # Versión de Node.js a usar
  NODE_VERSION = "18"

# Configuración para Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos de imágenes
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
